### ISSUE TITLE
ReceiverStatus incorrect

### ISSUE THREAD

**Issue by saedelman** [svoop/ogn_client-ruby#6]
Your example for a ReceiverStatus is incorrect. The slash (/) after the first colon should be a greater than (>) sign. Otherwise, it is interpreted as an incorrectly formatted ReceiverBeacon packet.

Your example:
`LKHS>APRS,TCPIP*,qAC,GLIDERN2:/211635h v0.2.6.ARM CPU:0.2 RAM:777.7/972.2MB NTP:3.1ms/-3.8ppm 4.902V 0.583A +33.6C 14/16Acfts[1h] RF:+62-0.8ppm/+33.66dB/+19.4dB@10km[112619]/+25.0dB@10km[8/15]`

Actual ReceiverStatus:

`EKAB>APRS,TCPIP*,qAC,GLIDERN1:>012807h v0.2.6.ARM CPU:0.3 RAM:764.2/972.2MB NTP:0.3ms/-1.4ppm +42.2C 0/0Acfts[1h] RF:+70-5.4ppm/-0.43dB/+15.8dB@10km[13761]/+14.7dB@10km[1/1]`

**Comment by acasadoalonso** [comment]
One of them is position the other status report

Enviado desde mi iPhone.
AC/.

**Comment by saedelman** [comment]
No, that is not correct. There is no position information in either of the two examples I provided.

The EKAB message was pulled directly from the Glidernet APRS.

**Comment by svoop** [comment]
@saedelman You're right, I fixed the ReceiverStatus example in the wiki.
